(()=>{const D={es:{brand:'MCV CONTROL ROOM',refresh:'ACTUALIZAR',reset:'RESETEAR',logout:'SALIR',label:'// GESTIÓN DE EQUIPOS',title:'CONTROL <span>ROOM.</span>',subtitle:'Revisa registros, gestiona brackets y exporta rosters.',add:'AGREGAR EQUIPO',export:'EXPORTAR CSV',all:'TODOS',pending:'PENDIENTE',approved:'APROBADO',rejected:'RECHAZADO',empty:'NO HAY EQUIPOS EN ESTA VISTA.',team:'EQUIPO',teamName:'Nombre del equipo',captain:'Capitán',players:'Jugadores',status:'Estado',notes:'Notas',save:'GUARDAR',cancel:'CANCELAR',lang:'EN'},en:{brand:'MCV CONTROL ROOM',refresh:'REFRESH',reset:'RESET',logout:'LOGOUT',label:'// TEAMS MANAGEMENT',title:'CONTROL <span>ROOM.</span>',subtitle:'Review registrations, manage brackets, export rosters.',add:'ADD TEAM',export:'EXPORT CSV',all:'ALL',pending:'PENDING',approved:'APPROVED',rejected:'REJECTED',empty:'NO TEAMS IN THIS VIEW.',team:'TEAM',teamName:'Team name',captain:'Captain',players:'Players',status:'Status',notes:'Notes',save:'SAVE',cancel:'CANCEL',lang:'ES'}};

if(sessionStorage.getItem('mcv-admin-auth')!=='ok'){location.href='/login';}
const K='mcv-admin-teams',L='mcv-lang';let lang=localStorage.getItem(L)||'es',filter='all',edit=null;let teams=JSON.parse(localStorage.getItem(K)||'[]');
if(!teams.length){teams=[{id:crypto.randomUUID(),name:'UFL',captain:'Stadiom',players:5,status:'approved',notes:'Core squad',roster:[{name:'Player1',steam:'7656119..1'},{name:'Player2',steam:'7656119..2'},{name:'Player3',steam:'7656119..3'},{name:'Player4',steam:'7656119..4'},{name:'Player5',steam:'7656119..5'}],createdAt:Date.now()}];localStorage.setItem(K,JSON.stringify(teams));}
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],t=k=>D[lang][k]||k,save=()=>localStorage.setItem(K,JSON.stringify(teams));
function i18n(){document.documentElement.lang=lang;$$('[data-i18n]').forEach(e=>e.innerHTML=t(e.dataset.i18n));$('#langBtn').textContent=t('lang');}
function list(){const q=$('#q').value.toLowerCase();let a=filter==='all'?teams:teams.filter(x=>x.status===filter);if(q)a=a.filter(x=>(x.name+x.captain+x.notes).toLowerCase().includes(q));const s=$('#sort').value;if(s==='name')a.sort((x,y)=>x.name.localeCompare(y.name));if(s==='players')a.sort((x,y)=>y.players-x.players);if(s==='new')a.sort((x,y)=>y.createdAt-x.createdAt);return a;}
function render(){const a=list();$('#cards').innerHTML=a.map(x=>`<article class='card'><div class='card-top'><h3>${x.name}</h3><span class='status ${x.status}'>${x.status}</span></div><div class='card-meta'><span>👑 ${x.captain}</span><span>${x.players}p</span></div><p>${x.notes||''}</p><ul>${(x.roster||[]).map((r,i)=>`<li>${String(i+1).padStart(2,'0')} ${r.name||'-'} · ${r.steam||'-'}</li>`).join('')}</ul><div class='card-actions'><button class='ghost' data-edit='${x.id}'>EDIT</button><button class='ghost' data-set='${x.id}:approved'>APPROVE</button><button class='danger' data-set='${x.id}:rejected'>REJECT</button><button class='danger' data-del='${x.id}'>DELETE</button></div></article>`).join('');$('#empty').style.display=a.length?'none':'block';const c={all:teams.length,pending:teams.filter(x=>x.status==='pending').length,approved:teams.filter(x=>x.status==='approved').length,rejected:teams.filter(x=>x.status==='rejected').length};$$('[data-filter]').forEach(b=>{b.classList.toggle('active',b.dataset.filter===filter);b.querySelector('span').textContent=c[b.dataset.filter];});}
function open(m){edit=m?.id||null;teamName.value=m?.name||'';captain.value=m?.captain||'';players.value=m?.players||5;status.value=m?.status||'pending';notes.value=m?.notes||'';for(let i=1;i<=5;i++){window['p'+i].value=m?.roster?.[i-1]?.name||'';window['sid'+i].value=m?.roster?.[i-1]?.steam||'';}teamDlg.showModal();}
langBtn.onclick=()=>{lang=lang==='es'?'en':'es';localStorage.setItem(L,lang);i18n();};refreshBtn.onclick=render;resetBtn.onclick=()=>{if(confirm(lang==='es'?'¿Borrar todo?':'Delete all?')){teams=[];save();render();}};addBtn.onclick=()=>open();exportBtn.onclick=()=>{const h=['name','captain','players','status','notes'];const rows=teams.map(x=>h.map(k=>`"${String(x[k]||'').replace(/"/g,'""')}"`).join(','));const b=new Blob([[h.join(','),...rows].join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='mcv-teams.csv';a.click();};cancelBtn.onclick=()=>teamDlg.close();q.oninput=render;sort.onchange=render;$$('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render();});
document.addEventListener('click',e=>{const ed=e.target.closest('[data-edit]'),dl=e.target.closest('[data-del]'),st=e.target.closest('[data-set]');if(ed)open(teams.find(x=>x.id===ed.dataset.edit));if(dl){teams=teams.filter(x=>x.id!==dl.dataset.del);save();render();}if(st){const [id,n]=st.dataset.set.split(':');teams=teams.map(x=>x.id===id?{...x,status:n}:x);save();render();}});
teamForm.onsubmit=e=>{e.preventDefault();const roster=[1,2,3,4,5].map(i=>({name:window['p'+i].value.trim(),steam:window['sid'+i].value.trim()}));const p={id:edit||crypto.randomUUID(),name:teamName.value.trim(),captain:captain.value.trim(),players:+players.value,status:status.value,notes:notes.value.trim(),roster,createdAt:edit?(teams.find(x=>x.id===edit)?.createdAt||Date.now()):Date.now()};teams=edit?teams.map(x=>x.id===edit?p:x):[p,...teams];save();teamDlg.close();render();};
i18n();render();

function renderEventsAdmin(){const box=document.getElementById('event-admin-list'); if(!box||!window.MCVEvents)return; const events=MCVEvents.all(); box.innerHTML=events.map(e=>`<div class='card'><b>${e.name}</b> · ${e.status} · ${e.date||''} <button class='ghost' data-arch='${e.id}'>${e.status==='archived'?'Activar':'Archivar'}</button> <button class='danger' data-del-ev='${e.id}'>Eliminar</button></div>`).join('');}
const ef=document.getElementById('event-form'); if(ef){ef.onsubmit=(e)=>{e.preventDefault(); const events=MCVEvents.all(); events.unshift({id:crypto.randomUUID(),name:document.getElementById('ev-name').value,prizePool:document.getElementById('ev-prize').value,rules:document.getElementById('ev-rules').value,teamSize:+document.getElementById('ev-size').value,maxTeams:+document.getElementById('ev-max').value,format:document.getElementById('ev-format').value,date:document.getElementById('ev-date').value,time:document.getElementById('ev-time').value,status:'active'}); MCVEvents.save(events); ef.reset(); renderEventsAdmin();};}
document.addEventListener('click',e=>{const a=e.target.closest('[data-arch]'),d=e.target.closest('[data-del-ev]'); if(a){const ev=MCVEvents.all().map(x=>x.id===a.dataset.arch?{...x,status:x.status==='archived'?'active':'archived'}:x); MCVEvents.save(ev); renderEventsAdmin();} if(d){MCVEvents.save(MCVEvents.all().filter(x=>x.id!==d.dataset.delEv)); renderEventsAdmin();}});
renderEventsAdmin();
})();

const K='mcv-admin-teams',L='mcv-lang';let lang=localStorage.getItem(L)||'es',filter='all',edit=null;let teams=JSON.parse(localStorage.getItem(K)||'[]');
if(!teams.length){teams=[{id:crypto.randomUUID(),name:'UFL',captain:'Stadiom',players:5,status:'approved',notes:'Core squad',createdAt:Date.now()}];localStorage.setItem(K,JSON.stringify(teams));}
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],t=k=>D[lang][k]||k,save=()=>localStorage.setItem(K,JSON.stringify(teams));
function i18n(){document.documentElement.lang=lang;$$('[data-i18n]').forEach(e=>e.innerHTML=t(e.dataset.i18n));$('#langBtn').textContent=t('lang');}
function list(){const q=$('#q').value.toLowerCase();let a=filter==='all'?teams:teams.filter(x=>x.status===filter);if(q)a=a.filter(x=>(x.name+x.captain+x.notes).toLowerCase().includes(q));const s=$('#sort').value;if(s==='name')a.sort((x,y)=>x.name.localeCompare(y.name));if(s==='players')a.sort((x,y)=>y.players-x.players);if(s==='new')a.sort((x,y)=>y.createdAt-x.createdAt);return a;}
function render(){const a=list();$('#cards').innerHTML=a.map(x=>`<article class='card'><div class='card-top'><h3>${x.name}</h3><span class='status ${x.status}'>${x.status}</span></div><div class='card-meta'><span>👑 ${x.captain}</span><span>${x.players}p</span></div><p>${x.notes||''}</p><div class='card-actions'><button class='ghost' data-edit='${x.id}'>EDIT</button><button class='ghost' data-set='${x.id}:approved'>APPROVE</button><button class='danger' data-set='${x.id}:rejected'>REJECT</button><button class='danger' data-del='${x.id}'>DELETE</button></div></article>`).join('');$('#empty').style.display=a.length?'none':'block';const c={all:teams.length,pending:teams.filter(x=>x.status==='pending').length,approved:teams.filter(x=>x.status==='approved').length,rejected:teams.filter(x=>x.status==='rejected').length};$$('[data-filter]').forEach(b=>{b.classList.toggle('active',b.dataset.filter===filter);b.querySelector('span').textContent=c[b.dataset.filter];});}
function open(m){edit=m?.id||null;teamName.value=m?.name||'';captain.value=m?.captain||'';players.value=m?.players||5;status.value=m?.status||'pending';notes.value=m?.notes||'';teamDlg.showModal();}
langBtn.onclick=()=>{lang=lang==='es'?'en':'es';localStorage.setItem(L,lang);i18n();};refreshBtn.onclick=render;resetBtn.onclick=()=>{if(confirm(lang==='es'?'¿Borrar todo?':'Delete all?')){teams=[];save();render();}};addBtn.onclick=()=>open();exportBtn.onclick=()=>{const h=['name','captain','players','status','notes'];const rows=teams.map(x=>h.map(k=>`"${String(x[k]||'').replace(/"/g,'""')}"`).join(','));const b=new Blob([[h.join(','),...rows].join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='mcv-teams.csv';a.click();};cancelBtn.onclick=()=>teamDlg.close();q.oninput=render;sort.onchange=render;$$('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render();});
document.addEventListener('click',e=>{const ed=e.target.closest('[data-edit]'),dl=e.target.closest('[data-del]'),st=e.target.closest('[data-set]');if(ed)open(teams.find(x=>x.id===ed.dataset.edit));if(dl){teams=teams.filter(x=>x.id!==dl.dataset.del);save();render();}if(st){const [id,n]=st.dataset.set.split(':');teams=teams.map(x=>x.id===id?{...x,status:n}:x);save();render();}});
teamForm.onsubmit=e=>{e.preventDefault();const p={id:edit||crypto.randomUUID(),name:teamName.value.trim(),captain:captain.value.trim(),players:+players.value,status:status.value,notes:notes.value.trim(),createdAt:edit?(teams.find(x=>x.id===edit)?.createdAt||Date.now()):Date.now()};teams=edit?teams.map(x=>x.id===edit?p:x):[p,...teams];save();teamDlg.close();render();};


i18n();render();})();


