(function () {
const dict={es:{adminBrand:'MCV CONTROL ROOM',refresh:'REFRESH',reset:'RESET',logout:'LOGOUT',teamsMgmt:'// TEAMS MANAGEMENT',controlRoom:'CONTROL <span>ROOM.</span>',subtitle:'Review registrations, manage brackets, export rosters.',addTeam:'ADD TEAM',exportCsv:'EXPORT CSV',filterAll:'ALL',filterPending:'PENDING',filterApproved:'APPROVED',filterRejected:'REJECTED',empty:'NO TEAMS IN THIS VIEW.',modalTitle:'Equipo',teamName:'Nombre',captain:'Capitán',players:'Jugadores',status:'Estado',notes:'Notas',save:'Guardar',cancel:'Cancelar',langBtn:'EN'},en:{adminBrand:'MCV CONTROL ROOM',refresh:'REFRESH',reset:'RESET',logout:'LOGOUT',teamsMgmt:'// TEAMS MANAGEMENT',controlRoom:'CONTROL <span>ROOM.</span>',subtitle:'Review registrations, manage brackets, export rosters.',addTeam:'ADD TEAM',exportCsv:'EXPORT CSV',filterAll:'ALL',filterPending:'PENDING',filterApproved:'APPROVED',filterRejected:'REJECTED',empty:'NO TEAMS IN THIS VIEW.',modalTitle:'Team',teamName:'Name',captain:'Captain',players:'Players',status:'Status',notes:'Notes',save:'Save',cancel:'Cancel',langBtn:'ES'}};
const STORAGE='mcv-admin-teams', LANG='mcv-lang';
let lang=localStorage.getItem(LANG)||'es';
let teams=JSON.parse(localStorage.getItem(STORAGE)||'[]');
if(!teams.length){teams=[{id:crypto.randomUUID(),name:'UFL',captain:'stadiom',players:5,status:'approved',notes:'76561199.. · stadiom',createdAt:Date.now()-10000},{id:crypto.randomUUID(),name:'Scandi',captain:'Bomba',players:5,status:'pending',notes:'76561199.. · _bomba',createdAt:Date.now()-20000}];localStorage.setItem(STORAGE,JSON.stringify(teams));}
let filter='all',editId=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], t=k=>dict[lang][k]||k;
function i18n(){document.documentElement.lang=lang;$$('[data-i18n]').forEach(e=>e.innerHTML=t(e.dataset.i18n));$('#lang-toggle').textContent=t('langBtn');}
function save(){localStorage.setItem(STORAGE,JSON.stringify(teams));}
function getData(){const q=$('#search-input').value.toLowerCase().trim();let list=filter==='all'?teams:teams.filter(x=>x.status===filter);if(q)list=list.filter(x=>[x.name,x.captain,x.notes].join(' ').toLowerCase().includes(q));const s=$('#sort-by').value;if(s==='name')list.sort((a,b)=>a.name.localeCompare(b.name));if(s==='players')list.sort((a,b)=>b.players-a.players);if(s==='new')list.sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));return list;}
function card(team){return `<article class="team-card"><div class="team-card-top"><div><h3>${team.name}</h3><small>👑 ${team.captain}</small></div><span class="status ${team.status}">${team.status}</span></div><div class="team-meta"><span>${team.players} players</span><span>${new Date(team.createdAt||Date.now()).toLocaleDateString()}</span></div><p>${team.notes||'-'}</p><div class="team-actions"><button class="mini-btn" data-edit="${team.id}">EDIT</button><button class="mini-btn" data-status="${team.id}" data-next="approved">APPROVE</button><button class="mini-btn danger" data-status="${team.id}" data-next="rejected">REJECT</button><button class="mini-btn danger" data-del="${team.id}">DELETE</button></div></article>`}
function render(){const data=getData();$('#cards-wrap').innerHTML=data.map(card).join('');$('#empty-state').style.display=data.length?'none':'block';const c={all:teams.length,pending:teams.filter(x=>x.status==='pending').length,approved:teams.filter(x=>x.status==='approved').length,rejected:teams.filter(x=>x.status==='rejected').length};$$('[data-filter]').forEach(b=>{b.classList.toggle('active',b.dataset.filter===filter);b.querySelector('span').textContent=c[b.dataset.filter];});}
function openModal(team){editId=team?.id||null;$('#team-name').value=team?.name||'';$('#team-captain').value=team?.captain||'';$('#team-players').value=team?.players||5;$('#team-status').value=team?.status||'pending';$('#team-notes').value=team?.notes||'';$('#team-modal').showModal();}
function exportCsv(){const h=['name','captain','players','status','notes'];const r=teams.map(t=>h.map(k=>`"${String(t[k]??'').replace(/"/g,'""')}"`).join(','));const blob=new Blob([[h.join(','),...r].join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mcv-teams.csv';a.click();}
$('#lang-toggle').onclick=()=>{lang=lang==='es'?'en':'es';localStorage.setItem(LANG,lang);i18n();};
$('#add-team').onclick=()=>openModal();$('#export-csv').onclick=exportCsv;$('#refresh').onclick=render;$('#reset-all').onclick=()=>{if(confirm('Reset all teams?')){teams=[];save();render();}};
$$('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render();});$('#search-input').oninput=render;$('#sort-by').onchange=render;
document.addEventListener('click',e=>{const ed=e.target.closest('[data-edit]'),del=e.target.closest('[data-del]'),st=e.target.closest('[data-status]');if(ed)openModal(teams.find(t=>t.id===ed.dataset.edit));if(del){teams=teams.filter(t=>t.id!==del.dataset.del);save();render();}if(st){teams=teams.map(t=>t.id===st.dataset.status?{...t,status:st.dataset.next}:t);save();render();}});
$('#team-form').addEventListener('submit',e=>{e.preventDefault();const p={id:editId||crypto.randomUUID(),name:$('#team-name').value.trim(),captain:$('#team-captain').value.trim(),players:Number($('#team-players').value),status:$('#team-status').value,notes:$('#team-notes').value.trim(),createdAt:editId?(teams.find(t=>t.id===editId)?.createdAt||Date.now()):Date.now()};teams=editId?teams.map(t=>t.id===editId?p:t):[p,...teams];save();$('#team-modal').close();render();});
i18n();render();
})();
